.build: &build
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker version
    - docker build --build-arg BASE_IMAGE=${BASE_IMAGE} --build-arg PACKAGE_MANAGER=${PACKAGE_MANAGER} ${DOCKER_BUILD_ARGS} -t ${CI_REGISTRY_IMAGE}/${DISTRO}:${CI_COMMIT_SHA} src/
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}/${DISTRO}:${CI_COMMIT_SHA}

build:archlinux:
  <<: *build
  variables:
    DISTRO: archlinux
    BASE_IMAGE: base/archlinux
    PACKAGE_MANAGER: pacman

build:debian:
  <<: *build
  variables:
    DISTRO: debian
    BASE_IMAGE: debian
    PACKAGE_MANAGER: apt-get

build:ubuntu:
  <<: *build
  variables:
    DISTRO: ubuntu
    BASE_IMAGE: ubuntu
    PACKAGE_MANAGER: apt-get
